/* (c) Copyright Frontify Ltd., all rights reserved. */

export const DEFAULT_COLOR_SQUARE_WIDTH = 100;
export const MINIMUM_COLOR_WIDTH_TO_ALLOW_RESIZING = 18;
export const MINIMUM_AMOUNT_OF_PIXELS_TO_MOVE_DURING_RESIZE = 8;
export const MINIMUM_AMOUNT_OF_PIXELS_TO_SHIFT_WHEN_ADDING_NEW_COLOR = 18;
export const EMPTY_BLOCK_COLORS = ['#D5D6D6', '#DFDFDF', '#E8E9E9', '#F1F1F1', '#FAFAFA', '#FFFFFF'];
