/* (c) Copyright Frontify Ltd., all rights reserved. */

export const DEFAULT_COLOR_SQUARE_WIDTH = 100;
export const MINIMUM_COLOR_WIDTH = 9;
export const WIDTH_LIMIT = MINIMUM_COLOR_WIDTH * 2;
export const MINIMUM_AMOUNT_OF_PIXELS_TO_MOVE_DURING_RESIZE = MINIMUM_COLOR_WIDTH;
export const MINIMUM_AMOUNT_OF_PIXELS_TO_SHIFT_WHEN_ADDING_NEW_COLOR = MINIMUM_COLOR_WIDTH * 2;
export const EMPTY_BLOCK_COLORS = ['#D5D6D6', '#DFDFDF', '#E8E9E9', '#F1F1F1', '#FAFAFA', '#FFFFFF'];
export const MINIMUM_NUMBER_OF_COLORS = 1;
export const MAXIMUM_NUMBER_OF_PLACEHOLDER_SQUARES = 6;
export const DROP_ZONE_WIDTH = 100;
export const DEFAULT_COLOR_PICKER_FLYOUT_COLOR = {
    red: 0,
    green: 0,
    blue: 0,
    alpha: 1,
};
export const MINIMUM_WIDTH_TO_SHOW_TRASH_ICON_AT_NEGATIVE_RIGHT_POSITION = 24;
export const MINIMUM_WIDTH_TO_SHOW_TRASH_ICON_AT_FURTHEST_RIGHT_POSITION = 32;
export const COLOR_SCALE_BLOCK_OUTER_HORIZONTAL_PADDING = 3;
export const COLOR_SQUARE_SPACING = 1;
export const COLOR_SCALE_BLOCK_BORDER_WIDTH = 2;
