/* (c) Copyright Frontify Ltd., all rights reserved. */

import { Palette } from './types';

const paletteMock: Palette[] = [
    {
        id: 'palette02',
        name: 'Palette 02',
        colors: [
            {
                id: 20,
                name: 'Black',
                sort: 1,
                nameCss: 'black',
                red: 0,
                green: 0,
                blue: 0,
                alpha: 255,
                hex: '#000000',
                hue: 0,
                saturation: 0,
                lightness: 0,
                c: 0,
                m: 0,
                y: 0,
                k: 100,
                pantone: null,
                ral: null,
                oracal: null,
                pantoneCoated: null,
                pantoneUncoated: null,
                cmykCoated: null,
                cmykUncoated: null,
                cmykNewspaper: null,
                ncs: null,
                pantoneCp: null,
                pantonePlastics: null,
                pantoneTextile: null,
                hks: null,
                threeM: null,
                lab: null,
            },
            {
                id: 21,
                name: 'White',
                sort: 2,
                nameCss: 'white',
                red: 255,
                green: 255,
                blue: 255,
                alpha: 255,
                hex: '#3f2456',
                hue: 0,
                saturation: 0,
                lightness: 100,
                c: 0,
                m: 0,
                y: 0,
                k: 0,
                pantone: null,
                ral: null,
                oracal: null,
                pantoneCoated: null,
                pantoneUncoated: null,
                cmykCoated: null,
                cmykUncoated: null,
                cmykNewspaper: null,
                ncs: null,
                pantoneCp: null,
                pantonePlastics: null,
                pantoneTextile: null,
                hks: null,
                threeM: null,
                lab: null,
            },
        ],
    },
    {
        id: 'palette888',
        name: 'Palette 888',
        colors: [
            {
                id: 20,
                name: 'Black',
                sort: 1,
                nameCss: 'black',
                red: 0,
                green: 0,
                blue: 0,
                alpha: 255,
                hex: '#d96173',
                hue: 0,
                saturation: 0,
                lightness: 0,
                c: 0,
                m: 0,
                y: 0,
                k: 100,
                pantone: null,
                ral: null,
                oracal: null,
                pantoneCoated: null,
                pantoneUncoated: null,
                cmykCoated: null,
                cmykUncoated: null,
                cmykNewspaper: null,
                ncs: null,
                pantoneCp: null,
                pantonePlastics: null,
                pantoneTextile: null,
                hks: null,
                threeM: null,
                lab: null,
            },
            {
                id: 21,
                name: 'White',
                sort: 2,
                nameCss: 'white',
                red: 255,
                green: 255,
                blue: 255,
                alpha: 255,
                hex: '#fffff',
                hue: 0,
                saturation: 0,
                lightness: 100,
                c: 0,
                m: 0,
                y: 0,
                k: 0,
                pantone: null,
                ral: null,
                oracal: null,
                pantoneCoated: null,
                pantoneUncoated: null,
                cmykCoated: null,
                cmykUncoated: null,
                cmykNewspaper: null,
                ncs: null,
                pantoneCp: null,
                pantonePlastics: null,
                pantoneTextile: null,
                hks: null,
                threeM: null,
                lab: null,
            },
        ],
    },
    {
        id: 'halloweenPalette',
        name: 'Halloween Palette',
        colors: [
            {
                id: 20,
                name: 'Black',
                sort: 1,
                nameCss: 'black',
                red: 0,
                green: 0,
                blue: 0,
                alpha: 255,
                hex: '#edb1dd',
                hue: 0,
                saturation: 0,
                lightness: 0,
                c: 0,
                m: 0,
                y: 0,
                k: 100,
                pantone: null,
                ral: null,
                oracal: null,
                pantoneCoated: null,
                pantoneUncoated: null,
                cmykCoated: null,
                cmykUncoated: null,
                cmykNewspaper: null,
                ncs: null,
                pantoneCp: null,
                pantonePlastics: null,
                pantoneTextile: null,
                hks: null,
                threeM: null,
                lab: null,
            },
            {
                id: 21,
                name: 'White',
                sort: 2,
                nameCss: 'white',
                red: 255,
                green: 255,
                blue: 255,
                alpha: 255,
                hex: '#ffffff',
                hue: 0,
                saturation: 0,
                lightness: 100,
                c: 0,
                m: 0,
                y: 0,
                k: 0,
                pantone: null,
                ral: null,
                oracal: null,
                pantoneCoated: null,
                pantoneUncoated: null,
                cmykCoated: null,
                cmykUncoated: null,
                cmykNewspaper: null,
                ncs: null,
                pantoneCp: null,
                pantonePlastics: null,
                pantoneTextile: null,
                hks: null,
                threeM: null,
                lab: null,
            },
        ],
    },
];

export const useColorPalettes = (colorPalettes: string[]) => {
    return paletteMock.filter((palette) => colorPalettes.includes(palette.id.toString()));
};
