/* (c) Copyright Frontify Ltd., all rights reserved. */

import { describe, expect, test } from 'vitest';
import { mapColorPalettes } from './mapColorPalettes';

describe('mapColorPalettes', () => {
    test('should map app bridge color palette to fondue palette', () => {
        const result = mapColorPalettes([
            {
                id: 19,
                name: 'Awesome color palette',
                description: 'This is an awesome color palette, which can be selected on the "Color Kit" block above ^',
                colors: [
                    {
                        id: 6,
                        name: 'Tarawera',
                        sort: 1,
                        nameCss: 'tarawera',
                        hex: '0b486b',
                        red: 11,
                        green: 72,
                        blue: 107,
                        alpha: 255,
                        hue: 202,
                        saturation: 81,
                        lightness: 23,
                        c: 90,
                        m: 33,
                        y: 0,
                        k: 58,
                        pantone: null,
                        ral: null,
                        oracal: null,
                        pantoneCoated: null,
                        pantoneUncoated: null,
                        cmykCoated: null,
                        cmykUncoated: null,
                        cmykNewspaper: null,
                        ncs: null,
                        pantoneCp: null,
                        pantonePlastics: null,
                        pantoneTextile: null,
                        hks: null,
                        threeM: null,
                        lab: null,
                    },
                    {
                        id: 7,
                        name: 'Oracle',
                        sort: 2,
                        nameCss: 'oracle',
                        hex: '3b8686',
                        red: 59,
                        green: 134,
                        blue: 134,
                        alpha: 255,
                        hue: 180,
                        saturation: 39,
                        lightness: 38,
                        c: 56,
                        m: 0,
                        y: 0,
                        k: 47,
                        pantone: null,
                        ral: null,
                        oracal: null,
                        pantoneCoated: null,
                        pantoneUncoated: null,
                        cmykCoated: null,
                        cmykUncoated: null,
                        cmykNewspaper: null,
                        ncs: null,
                        pantoneCp: null,
                        pantonePlastics: null,
                        pantoneTextile: null,
                        hks: null,
                        threeM: null,
                        lab: null,
                    },
                    {
                        id: 8,
                        name: 'Silver Tree',
                        sort: 3,
                        nameCss: 'silver-tree',
                        hex: '79bd9a',
                        red: 121,
                        green: 189,
                        blue: 154,
                        alpha: 255,
                        hue: 149,
                        saturation: 34,
                        lightness: 61,
                        c: 36,
                        m: 0,
                        y: 19,
                        k: 26,
                        pantone: null,
                        ral: null,
                        oracal: null,
                        pantoneCoated: null,
                        pantoneUncoated: null,
                        cmykCoated: null,
                        cmykUncoated: null,
                        cmykNewspaper: null,
                        ncs: null,
                        pantoneCp: null,
                        pantonePlastics: null,
                        pantoneTextile: null,
                        hks: null,
                        threeM: null,
                        lab: null,
                    },
                ],
            },
        ]);
        expect(result).toEqual([
            {
                id: 19,
                title: 'Awesome color palette',
                colors: [
                    {
                        alpha: 1,
                        red: 11,
                        green: 72,
                        blue: 107,
                        name: 'Tarawera',
                    },
                    {
                        alpha: 1,
                        red: 59,
                        green: 134,
                        blue: 134,
                        name: 'Oracle',
                    },
                    {
                        alpha: 1,
                        red: 121,
                        green: 189,
                        blue: 154,
                        name: 'Silver Tree',
                    },
                ],
            },
        ]);
    });
});
