name: Continuous Integration

on:
    pull_request:
    push:
        branches:
            - main

env:
    CI: true

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v2

            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Cache NPM dependencies
              id: npm_cache
              uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json') }}

            - name: Install NPM dependencies
              if: steps.npm_cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Install NPM dependencies from packages
              if: steps.npm_cache.outputs.cache-hit != 'true'
              run: npm run bootstrap

            - name: Cache Cypress binary
              id: cypress_cache
              uses: actions/cache@v2
              with:
                  path: ~/.cache/Cypress
                  key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}

            - name: Typecheck files
              run: npm run typecheck

            - name: Lint files (JS/TS & CSS)
              run: npm run lint

            - name: Test Functionality
              run: npm run test:unit

            - name: Test Components
              run: npm run test:functional:ci
