name: Continuous Integration

# Ensures that only one workflow per branch will run at a time.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    pull_request:
    push:
        branches:
            - main

env:
    NODE_VERSION: 16
    CI: true
    NUMBER_OF_RUNNERS: 7

jobs:
    linting:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint files (JS/TS & CSS)
              run: pnpm run lint

    typecheck:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build packages
              run: pnpm run build

            - name: Typecheck files
              run: pnpm run typecheck

    unit-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Unit Tests
              run: pnpm run test:unit

    component-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                containers: [0, 1, 2, 3, 4, 5, 6]

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build packages
              run: pnpm run build

            - name: Component tests
              uses: cypress-io/github-action@v4.2.0
              with:
                  install: false
                  component: true
                  spec: $(node ./.github/lib/cypress-matrix.js ${{ env.NUMBER_OF_RUNNERS }} ${{ matrix.containers }})
